version: '3'

services:
  postgresql:
    image: postgres
    container_name: movie-library
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=movie-library
      - POSTGRES_PASSWORD=movieLibrary2024
      - POSTGRES_DATABASE=movie-library
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-movie-library
    ports:
      - '6379-6379'